/*
 * Tang Nano 4K SoC Top-Level Verilog (GW1NSR-4C)
 *
 * Integrated Components:
 * - ARM Cortex-M3 Hard Core (Gowin_EMPU_M3)
 * - UART0 routed to Pins 18 (TX) and 19 (RX)
 * - SPI Flash Interface (AHB, 0x60000000, XIP)
 * - PSRAM Memory Interface (APB Slot 2, 0x40002500)
 * - APB2 Expansion Slot 1 for Tiny Tapeout (TT) (0x40002400)
 */

`default_nettype none

module tang_nano_4k_top (
    input  wire clk_27m,      // Pin 45

    // UART0
    output wire uart_tx,      // Pin 18
    input  wire uart_rx,      // Pin 19

    // SPI Flash (XIP)
    output wire flash_cs_n,   // Pin 36
    output wire flash_sclk,   // Pin 37
    output wire flash_mosi,   // Pin 38
    input  wire flash_miso    // Pin 39
);

    // --- Internal Reset Logic ---
    reg [7:0] reset_cnt = 8'h0;
    wire sys_reset_n = &reset_cnt;
    always @(posedge clk_27m) begin
        if (!sys_reset_n) reset_cnt <= reset_cnt + 1'b1;
    end

    // --- AHB Expansion Bus (For Flash XIP) ---
    wire [31:0] ahb_addr;
    wire [31:0] ahb_wdata;
    wire [31:0] ahb_rdata;
    wire        ahb_write;
    wire [1:0]  ahb_trans;
    wire        ahb_ready;
    wire        ahb_hsel_flash;

    // AHB Address Decoding (Flash: 0x60000000)
    assign ahb_hsel_flash = (ahb_addr[31:28] == 4'h6);

    wire [31:0] flash_rdata;
    wire        flash_ready;

    // AHB Data Phase Multiplexing
    assign ahb_rdata = flash_rdata;
    assign ahb_ready = ahb_hsel_flash ? flash_ready : 1'b1;

    // --- APB2 Expansion Bus ---
    wire [11:0] apb_paddr;   // 12-bit address for 4KB expansion range
    wire [31:0] apb_pwdata;
    wire [31:0] apb_prdata_tt;
    wire [31:0] apb_prdata_psram;
    wire [31:0] apb_prdata;
    wire        apb_psel;    // Shared Select
    wire        apb_penable;
    wire        apb_pwrite;
    wire        apb_pready_tt;
    wire        apb_pready_psram;
    wire        apb_pready;

    // APB Slot Decoding
    // Slot 1 (TT):    0x40002400 (Offset 0x400) -> PADDR[11:8] = 4'h4
    // Slot 2 (PSRAM): 0x40002500 (Offset 0x500) -> PADDR[11:8] = 4'h5
    wire apb_psel_tt    = apb_psel && (apb_paddr[11:8] == 4'h4);
    wire apb_psel_psram = apb_psel && (apb_paddr[11:8] == 4'h5);

    assign apb_prdata = apb_psel_tt    ? apb_prdata_tt :
                        apb_psel_psram ? apb_prdata_psram : 32'h0;
    assign apb_pready = apb_psel_tt    ? apb_pready_tt :
                        apb_psel_psram ? apb_pready_psram : 1'b1;

    // --- M3 IP Core Instantiation ---
    Gowin_EMPU_M3 m3_inst (
        .MSSCLK      (clk_27m),
        .UART0RXD    (uart_rx),
        .UART0TXD    (uart_tx),

        // AHB Expansion
        .HADDR       (ahb_addr),
        .HWDATA      (ahb_wdata),
        .HRDATA      (ahb_rdata),
        .HWRITE      (ahb_write),
        .HTRANS      (ahb_trans),
        .HREADY      (ahb_ready),

        // APB2 Expansion
        .PSEL        (apb_psel),
        .PENABLE     (apb_penable),
        .PADDR       (apb_paddr),
        .PWRITE      (apb_pwrite),
        .PWDATA      (apb_pwdata),
        .PRDATA      (apb_prdata),
        .PREADY      (apb_pready)
    );

    // --- SPI Flash Interface (AHB Bridge) ---
    SPI_Flash_Interface flash_inst (
        .hclk        (clk_27m),
        .hreset_n    (sys_reset_n),
        .hsel        (ahb_hsel_flash),
        .haddr       (ahb_addr),
        .hwrite      (ahb_write),
        .htrans      (ahb_trans),
        .hwdata      (ahb_wdata),
        .hrdata      (flash_rdata),
        .hready      (flash_ready),

        // External Pins
        .flash_cs_n  (flash_cs_n),
        .flash_clk   (flash_sclk),
        .flash_mosi  (flash_mosi),
        .flash_miso  (flash_miso)
    );

    // --- PSRAM Memory Interface (APB Bridge) ---
    PSRAM_APB_Interface psram_inst (
        .pclk        (clk_27m),
        .preset_n    (sys_reset_n),
        .psel        (apb_psel_psram),
        .paddr       (apb_paddr[7:0]), // 256B range
        .pwrite      (apb_pwrite),
        .penable     (apb_penable),
        .pwdata      (apb_pwdata),
        .prdata      (apb_prdata_psram),
        .pready      (apb_pready_psram)
    );

    // --- Tiny Tapeout Wrapper (APB2 Slot 1) ---
    tt_m3_wrapper tt_bridge (
        .PCLK        (clk_27m),
        .PRESETn     (sys_reset_n),
        .PADDR       (apb_paddr[7:0]), // 256B range
        .PSEL        (apb_psel_tt),
        .PENABLE     (apb_penable),
        .PWRITE      (apb_pwrite),
        .PWDATA      (apb_pwdata),
        .PRDATA      (apb_prdata_tt),
        .PREADY      (apb_pready_tt)
    );

endmodule

// --- Placeholder Module Definitions (Typically generated by Gowin IP Generator) ---

module SPI_Flash_Interface (
    input  wire        hclk,
    input  wire        hreset_n,
    input  wire        hsel,
    input  wire [31:0] haddr,
    input  wire        hwrite,
    input  wire [1:0]  htrans,
    input  wire [31:0] hwdata,
    output wire [31:0] hrdata,
    output wire        hready,
    output wire        flash_cs_n,
    output wire        flash_clk,
    output wire        flash_mosi,
    input  wire        flash_miso
);
    // Simple AHB-Lite Dummy Slave
    assign hrdata = 32'hDEADBEEF; // ID for testing
    assign hready = 1'b1;
endmodule

module PSRAM_APB_Interface (
    input  wire        pclk,
    input  wire        preset_n,
    input  wire        psel,
    input  wire [7:0]  paddr,
    input  wire        pwrite,
    input  wire        penable,
    input  wire [31:0] pwdata,
    output wire [31:0] prdata,
    output wire        pready
);
    // Simple APB Dummy Slave for PSRAM Control
    assign prdata = 32'hCAFEBABE;
    assign pready = 1'b1;
endmodule
