// Automatically generated by make_root_pointers.py.

const char *readline_hist[(8)];
mp_obj_list_t mp_sys_argv_obj;
mp_obj_t pin_irq_handler[16];
mp_obj_t sys_mutable[MP_SYS_MUTABLE_NUM];
mp_sched_item_t sched_queue[(4)];
struct _machine_pin_obj_t *pin_obj[16];
struct _machine_pwm_obj_t *active_pwm[8];
struct _machine_timer_obj_t *active_timers[4];
struct _mp_vfs_mount_t *vfs_cur;
struct _mp_vfs_mount_t *vfs_mount_table;
